services:
  # Database
  postgres:
    image: postgres:16
    container_name: clinic-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: clinicdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - clinic-net
  

  # Authentication / Authorization
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: token-exchange
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json
    networks:
      - clinic-net    


  # Service Discovery
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8070:8070"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - clinic-net
  

  # Service Routing
  gateway-server:
    build: ./gateway-server
    container_name: gateway-server
    ports:
      - "8071:8071"
    depends_on:
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - clinic-net
  

  # Distributed Tracing
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - clinic-net
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    networks:
      - clinic-net
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    container_name: logstash
    ports:
      - "5000:5000"
    command:
      logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./config:/etc/logstash/conf.d
    networks:
      - clinic-net

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    depends_on:
      - elasticsearch
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=elasticsearch
      - "ES_HOSTS=http://elasticsearch:9300"
    networks:
      - clinic-net
  

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - clinic-net

  grafana:
    image: "grafana/grafana:latest"
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - clinic-net
  

  # Custom Microservices
  inventory-management:
    build: ./inventory-management
    container_name: inventory-management
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://clinic-postgres:5432/clinicdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    networks:
      - clinic-net

  test-sample-management:
    build: ./test-sample-management
    container_name: test-sample-management
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://clinic-postgres:5432/clinicdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    networks:
      - clinic-net

  patient-provider-management:
    build: ./patient-provider-management
    container_name: patient-provider-management
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://clinic-postgres:5432/clinicdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    networks:
      - clinic-net
      

# Misc.
volumes:
  pgdata:
  esdata1:
    driver: local

networks:
  clinic-net:
    driver: bridge