spring.application.name=eureka-server
server.port=8070

# Eureka Configuration
eureka.client.service-url.defaultZone=http://eureka-server:8070/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false