spring.application.name=inventory-management
server.port=8081

# Eureka Configuration
eureka.client.service-url.defaultZone=http://eureka-server:8070/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Postgres Configuration
spring.datasource.url=jdbc:postgresql://clinic-postgres:5432/clinicdb
spring.datasource.username=user
spring.datasource.password=pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Distributed Tracing Configuration
management.tracing.enabled=true
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
logging.level.io.micrometer.tracing=INFO
logging.level.zipkin2=INFO

# Prometheus Configuration
management.endpoints.web.exposure.include=prometheus